import { z } from "zod";
import { registry } from "@/lib/openapi";
import { LocalizedTextSchema } from "@/server/shared/schemas";

// settings_kv key "doubt_zone_safety" (Phase 7 kickoff decisions,
// docs/ARCHITECTURE.md) - every field here is admin-editable without a
// redeploy, since a wrong helpline number or an over/under-sensitive
// classifier threshold are corrections a founder needs to make
// immediately, not on the next release.
export const DoubtZoneSafetySettingsSchema = z.object({
  // See classifyMessageSafety (./safety.ts): true (the default) flags a
  // message on ANY non-"none" classifier category, no confidence cutoff -
  // deliberately biased toward false positives per the founder's explicit
  // instruction ("a wrongly flagged message costs a staff member ten
  // seconds; a missed one could matter a great deal"). Only loosen this
  // once real false-positive volume from actual usage shows it's needed.
  flagOnAnySignal: z.boolean(),
  // Shown verbatim to the learner the instant the classifier flags their
  // message - never generated by the model itself, so the exact wording
  // (and the helpline numbers inside it) can be corrected instantly
  // without trusting a live model call to relay them accurately.
  safetyRedirectMessage: LocalizedTextSchema,
  // Shown when the output-filter circuit breaker cuts a reply mid-stream
  // for advice-like language (see ./reply.ts) - a fixed, safe substitute
  // for whatever partial sentence was cut off, never the partial text
  // itself.
  adviceLanguageFallbackMessage: LocalizedTextSchema,
  // Shown on a genuine mid-stream failure (the Anthropic call itself
  // errors after streaming has already started, e.g. a transient API
  // outage) - not a safety or advice-language event, just "please try
  // again," but still a fixed, deterministic substitute rather than
  // whatever partial text had streamed so far.
  temporaryUnavailableMessage: LocalizedTextSchema,
  // Shown once at the start of every new Doubt Zone thread (Phase 7
  // kickoff decision): upfront, honest, non-scary disclosure that this is
  // an AI, not a person, can't give investment advice, and a flagged
  // message may be reviewed by a Finlamma staff member.
  threadDisclosureMessage: LocalizedTextSchema,
  perLearnerDailyMessageCap: z.number().int().positive(),
  globalDailyMessageCap: z.number().int().positive(),
});
export type DoubtZoneSafetySettings = z.infer<typeof DoubtZoneSafetySettingsSchema>;

// PENDING founder + qualified-person review before launch (see
// docs/ROADMAP.md's pre-launch checklist item added alongside this
// checkpoint) - same "seed as a clearly marked draft" pattern
// docs/ARCHITECTURE.md D5 already uses for legal_documents. Helpline
// numbers below were checked against wcd.gov.in and PIB press releases at
// the time this was written (2026-09-30), not pulled from memory - but
// Childline 1098 is actively being merged into the 112 emergency line
// state-by-state, so this must be re-verified close to launch, not trusted
// as permanently current.
export const DEFAULT_DOUBT_ZONE_SAFETY_SETTINGS: DoubtZoneSafetySettings = {
  flagOnAnySignal: true,
  safetyRedirectMessage: {
    en:
      "DRAFT - PENDING QUALIFIED REVIEW: That sounds like something important, and I want you to " +
      "talk to someone who can really help - not me. Please tell a parent, guardian, or another " +
      "adult you trust. You can also call Childline India, a free 24x7 helpline for children, at " +
      "1098, or the KIRAN mental health helpline at 1800-599-0019 (also works as 14416). " +
      "I'm here for money and finance questions whenever you're ready.",
    hi:
      "DRAFT - PENDING QUALIFIED REVIEW: Yeh baat important lagti hai, aur main chahta hoon ki aap " +
      "kisi aise insaan se baat karein jo sach mein madad kar sake - main nahi. Kripya apne " +
      "parents, guardian, ya kisi aur bharosemand adult ko batayein. Aap Childline India ko bhi " +
      "1098 par (bachchon ke liye free 24x7 helpline) ya KIRAN mental health helpline ko " +
      "1800-599-0019 (14416 bhi) par call kar sakte hain. Main paise aur finance ke sawaalon ke " +
      "liye hamesha yahan hoon.",
    hx:
      "DRAFT - PENDING QUALIFIED REVIEW: Yeh baat important lagti hai, aur main chahta hoon ki tum " +
      "kisi aise insaan se baat karo jo sach me help kar sake - main nahi. Please apne parents, " +
      "guardian, ya kisi trusted adult ko batao. Tum Childline India ko 1098 par (bachchon ke liye " +
      "free 24x7 helpline) ya KIRAN mental health helpline ko 1800-599-0019 (14416 bhi) par call " +
      "kar sakte ho. Main money aur finance ke questions ke liye hamesha yahan hoon.",
  },
  adviceLanguageFallbackMessage: {
    en:
      "Let me put that differently - I can explain how something works, but I can't tell you what " +
      "to buy, sell, or do with real money. Want me to explain the general idea instead?",
    hi:
      "Isse main alag tarah se samjhata hoon - main yeh bata sakta hoon ki koi cheez kaise kaam " +
      "karti hai, lekin yeh nahi bata sakta ki real paise se kya khareedna, bechna ya karna chahiye. " +
      "Kya main general idea samjhaun?",
    hx:
      "Isko main alag tarah se explain karta hoon - main yeh bata sakta hoon ki koi cheez kaise kaam " +
      "karti hai, lekin yeh nahi bata sakta ki real money se kya buy, sell ya karna chahiye. Chaho " +
      "toh main general idea explain kar doon?",
  },
  temporaryUnavailableMessage: {
    en: "Lamma AI is having trouble responding right now. Please try again in a moment.",
    hi: "Lamma AI abhi respond karne mein dikkat ho rahi hai. Kripya thodi der baad phir try karein.",
    hx: "Lamma AI abhi respond karne mein thodi dikkat aa rahi hai. Thodi der baad phir try karo.",
  },
  threadDisclosureMessage: {
    en:
      "Hi! I'm Lamma AI - a computer program, not a real person. I can help you understand money " +
      "and investing ideas, but I can't tell you what to actually buy or sell with real money. If " +
      "something you share ever raises a safety concern, a Finlamma team member may review it to " +
      "help keep you safe.",
    hi:
      "Hi! Main Lamma AI hoon - ek computer program, koi real insaan nahi. Main aapko paise aur " +
      "investing ke ideas samjhne mein madad kar sakta hoon, lekin yeh nahi bata sakta ki real paise " +
      "se kya khareedna ya bechna hai. Agar aap kuch aisa share karein jisse safety ki chinta ho, " +
      "toh aapko safe rakhne ke liye Finlamma team ka koi member use dekh sakta hai.",
    hx:
      "Hi! Main Lamma AI hoon - ek computer program, real insaan nahi. Main tumhe money aur " +
      "investing ke ideas samajhne mein help kar sakta hoon, lekin yeh nahi bata sakta ki real money " +
      "se kya buy ya sell karna hai. Agar tum kabhi kuch aisa share karo jisse safety ki concern ho, " +
      "toh tumhe safe rakhne ke liye Finlamma team ka koi member use dekh sakta hai.",
  },
  perLearnerDailyMessageCap: 40,
  globalDailyMessageCap: 2000,
};

export const DOUBT_ZONE_SAFETY_SETTINGS_KEY = "doubt_zone_safety";

// classifyMessageSafety's (./safety.ts) output shape.
export const SafetyCategorySchema = z.enum([
  "none",
  "self_harm_or_suicide",
  "abuse_or_neglect",
  "other_wellbeing_concern",
]);
export type SafetyCategory = z.infer<typeof SafetyCategorySchema>;

export const SafetyClassificationSchema = z.object({
  category: SafetyCategorySchema,
  // One short sentence the classifier gives for its own category choice -
  // stored as doubt_messages.flagged_reason so a staff reviewer sees why a
  // message was flagged without having to re-read the whole thread cold.
  reason: z.string(),
});
export type SafetyClassification = z.infer<typeof SafetyClassificationSchema>;

// --- App-facing (registered in OpenAPI) ---

export const ThreadIdParamSchema = z.object({ id: z.string().uuid() });

// Exactly one of lessonId/mentorId, enforced at the service layer (not
// here): lessonId set opens/resumes the in-lesson doubt_zone node's thread
// (mentor is derived server-side from the lesson's world, never trusted
// from the client); lessonId omitted opens/resumes the standalone Doubt
// Zone entry point (SET-14), where the client must say which mentor - the
// World Home screen already knows which mentor it's showing.
export const CreateThreadInputSchema = z.object({
  lessonId: z.string().uuid().optional().openapi({ description: "Open from an in-lesson Doubt Zone node." }),
  mentorId: z.string().uuid().optional().openapi({
    description: "Required when lessonId is omitted (the standalone Doubt Zone entry point).",
  }),
});
export type CreateThreadInput = z.infer<typeof CreateThreadInputSchema>;

export const ThreadResponseSchema = registry.register(
  "DoubtZoneThread",
  z.object({
    id: z.string().uuid(),
    mentorId: z.string().uuid(),
    lessonId: z.string().uuid().nullable(),
    // Shown once by the client at the top of a NEW thread (Phase 7 kickoff
    // decision) - already resolved to the caller's own language, so the
    // client doesn't need its own copy of every language's text.
    disclosureMessage: z.string(),
  }),
);

export const DoubtZoneMessageSchema = registry.register(
  "DoubtZoneMessage",
  z.object({
    id: z.string().uuid(),
    role: z.enum(["learner", "assistant"]),
    content: z.string(),
    createdAt: z.string().datetime(),
  }),
);

export const MessagesListResponseSchema = registry.register(
  "DoubtZoneMessagesListResponse",
  z.object({
    data: z.array(DoubtZoneMessageSchema),
    nextCursor: z.string().nullable(),
  }),
);

export const SendMessageInputSchema = z.object({
  content: z.string().trim().min(1).max(2000).openapi({ example: "What is a mutual fund?" }),
});
export type SendMessageInput = z.infer<typeof SendMessageInputSchema>;

// The streamed response body is newline-delimited JSON (one compact JSON
// object per line, `application/x-ndjson`) - not a JSON array and not SSE,
// chosen so the mobile client can parse it by splitting on "\n" with no SSE
// library dependency. "delta" lines repeat as the reply grows; exactly one
// "done" line always ends the stream. When "done".replaced is true, the
// client MUST discard whatever text it accumulated from "delta" lines and
// show replacementText instead - this covers the classifier-flagged case
// (no "delta" lines precede it at all - the redirect is instant, not
// streamed), the output-filter-cut case (some safe "delta" lines may have
// already streamed before the cut), and a genuine transient failure
// mid-stream. `replaced` is a transport-level "use replacementText, not the
// stream" flag - it is NOT the same thing as doubt_messages.flagged (a
// moderation/staff-visibility flag): a temporary-unavailable replacement is
// `replaced: true` but never a moderation flag, since nothing unsafe
// happened.
export const DoubtZoneStreamLineSchema = registry.register(
  "DoubtZoneStreamLine",
  z.union([
    z.object({ type: z.literal("delta"), text: z.string() }),
    z.object({
      type: z.literal("done"),
      messageId: z.string().uuid(),
      replaced: z.boolean(),
      replacementText: z.string().optional(),
    }),
  ]),
);
